name: chatting_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"  # Specify the Dart SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  lottie: ^3.1.2
  country_picker: ^2.0.26
  location: ^7.0.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  intl: ^0.19.0
  emoji_picker_flutter: ^3.1.0
  cached_network_image: ^3.4.1
 
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0
  
  
  

 

  

 

 
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Ensure the assets folder exists and contains images
  assets:
    - assets/images/
    - assets/animation/

  # If you plan to use custom fonts, define them here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
